backend:
  name: github
  repo: rafaazhimi/rafaazhimi.github.io
  branch: main

publish_mode: editorial_workflow

collections:
  - name: posts
    label: Posts
    folder: content/posts
    create: true
    slug: "{{slug}}"
    extension: json
    format: json
    summary: "{{title}}"
    fields:
      - label: ID
        name: id
        widget: hidden
        default: "{{slug}}"
      - label: Title
        name: title
        widget: string
        required: true
      - label: Content
        name: content
        widget: text
        required: true
      - label: External Link
        name: externalLink
        widget: string
        required: false
      - label: Created At
        name: createdAt
        widget: datetime
        required: true
        format: "YYYY-MM-DDTHH:mm:ss.SSSZ"
        default: "{{now}}"
      - label: Author
        name: author
        widget: string
        required: true
        default: "Admin"
